### ISSUE TITLE
Static public IP from a public ip subnet

### ISSUE THREAD

**Issue by Abhijeet-create** [ansible-collections/community.azure#11]
##### SUMMARY

To create static public ip from public ip prefix in azure https://docs.microsoft.com/en-us/azure/virtual-network/manage-public-ip-address-prefix#create-a-static-public-ip-address-from-a-prefix
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_publicipaddress
##### ADDITIONAL INFORMATION

With the help of this one can create public ip from already created public ip prefix range.

```yaml
azure_rm_publicipaddress:
       resource_group: myResourceGroup
       name: my_public_ip
       allocation_method: static
       public_ip_prefix_name: my_public_ip_prefix
```
