### ISSUE TITLE
Write Accelerator support

### ISSUE THREAD

**Issue by AndriyDmytrenko** [ansible-collections/community.azure#8]
##### SUMMARY

To enable Write Accelerator support for data disk (and OS disk probably as well) , this feature https://docs.microsoft.com/en-us/azure/virtual-machines/how-to-enable-write-accelerator

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_manageddisk
##### ADDITIONAL INFORMATION

The Write Accelerator support should be able to enable/disable write accelerator on a managed disk for supported VM SKUs, and supported disk cache settings. Would be nice also to have this checks before applying the configuration.

```yaml
azure_rm_manageddisk:
  name: "..."
  attach_caching: ""
  write_accelerator: "enabled"
```
